# Build the website from here
url: "https://try.discourse.org"
api_user: username
api_key: 0000000000000000000000000000000000000000000000000000000000000000
category: "blog"
output_dir: "dist/"
#static: # TODO make this configurable, defaulting to darksky style

# Import/sync articles into discourse (externally authored by users)
import:
  - class: Feed
    url: "http://www.feedforall.com/sample.xml"
    username: john
